ads/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import views

urlpatterns = [
    url(r'^kaspersky/$', views.kaspersky_android),
]

bitasync/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from bitasync_site import views


urlpatterns = [
    url(r'^$', views.homepage),
    url(r'^api-auth/', include('rest_framework.urls',namespace='rest_framework')),
    url(r'^162294.txt$', views.test_function),
    url(r'^about_us/', views.about_us),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^bitasync/', include('bitasync_site.urls')),
    url(r'^accounts/', include('user_profile.urls')),
    url(r'^code_test/', include('code_test.urls')),
    url(r'^coupons/', include('coupons.urls')),
    url(r'^guides/', include('guides.urls')),
    url(r'^payment/', include('payment.urls')),
    url(r'^shop_billing/', include('shop_billing.urls')),
    url(r'^ads/', include('ads.urls')),
    url(r'^access_control/', include('access_control.urls')),
    url(r'^telepromo_integration/', include('telepromo_integration.urls')),
]

user_profile/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout),
    url(r'^loggedin/$', views.loggedin),
    url(r'^invalid/$', views.invalid),
    url(r'^register/$', views.register),
    url(r'^register_success/$', views.register_success),
    url(r'^password_change/$', views.my_password_change),
	url(r'^my_password_change_done/$', views.my_password_change_done),
	url(r'^password_reset/$',views.my_password_reset,name='password_reset'),
    url(r'^password_reset_done/$', views.my_password_reset_done),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.my_password_reset_confirm,name='password_reset_confirm'), 
    url(r'^password_reset_complete$',views.my_password_reset_complete,name='password_reset_complete'),  
    url(r'^myprofile/$', views.myprofile),
]

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    is_shop = models.BooleanField()
    email_subscription = models.BooleanField(default=True)
    mobile = models.CharField(null=True, blank=True, max_length=20)

    def __unicode__(self):
        return "user_profile:" + self.user.username


class ShopProfile(models.Model):

    user_profile = models.OneToOneField(UserProfile)
    address = models.CharField(null=True, blank=True, max_length=100)
    landline = models.CharField(null=True, blank=True, max_length=20)
    bank_card_number = models.CharField(null=True, blank=True, max_length=20)
    account_holder = models.CharField(null=True, blank=True, max_length=30)
    reward = models.FloatField(default=0.0)
    debt = models.FloatField(default=0.0)

    def __unicode__(self):
        return "shop_profile:" + self.user_profile.user.username


class CustomerProfile(models.Model):

    user_profile = models.OneToOneField(UserProfile)
    latest_mobile = models.CharField(null=True, blank=True, max_length=30)

    def __unicode__(self):
        return "customer_profile:" + self.user_profile.user.username

user_profile/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User


class UserProfileForm(forms.Form): 
    # information that any customer provides during registration

    email = forms.EmailField(max_length=100)
    mobile = forms.CharField(max_length=20, required=False)
    is_shop = forms.BooleanField(required=False)    
    #email_subscription = forms.BooleanField(required=False)

    address = forms.CharField(max_length=100, required=False)
    landline = forms.CharField(max_length=20, required=False)  
    read_agreement = forms.BooleanField(required=True)
    
    def clean_email(self):

        email = self.cleaned_data["email"]
        users_with_existing_email = User.objects.filter(email=email)
        
        if users_with_existing_email: 
            raise forms.ValidationError('duplicate_email', code='duplicate_email')                
        else: 
            return email            


    
class MyProfileCustomerForm(forms.Form): 

    # do not show the username to the user. 
#    username = forms.CharField()
    email = forms.EmailField(max_length=100)
    mobile = forms.CharField(max_length=20, required=False)
    email_subscription = forms.BooleanField(required=False)
    
    def clean_email(self):

        email = self.cleaned_data['email']
        
        if "email" in self.changed_data: 
        
            # we should make sure that there is only one user with this new email.     
            
            email = self.cleaned_data["email"]
            users_with_existing_email = User.objects.filter(email=email)
        
            if users_with_existing_email: 
                raise forms.ValidationError('duplicate_email', code='duplicate_email')                
                
            else: 
                return email            
        
        else: 
            return email    
    
    
class MyProfileShopForm(forms.Form):
 
    email = forms.EmailField(max_length=100)
    mobile = forms.CharField(required=False)
    address = forms.CharField(max_length=100, required=False)
    landline = forms.CharField(max_length=20, required=False)  
    email_subscription = forms.BooleanField(required=False)
    
    # readonly field
    reward = forms.IntegerField(required=False) 
    bank_card_number = forms.CharField(max_length=100, required=False)
    account_holder = forms.CharField(max_length=100, required=False)
   
    def __init__(self,*args,**kwargs): 
        super(MyProfileShopForm,self).__init__(*args,**kwargs)
        self.fields['reward'].widget.attrs['readonly'] = True
        

    def clean_email(self):

        email = self.cleaned_data['email']
        
        if "email" in self.changed_data: 
        
            # we should make sure that there is only one user with this new email.     
            
            email = self.cleaned_data["email"]
            users_with_existing_email = User.objects.filter(email=email)
        
            if users_with_existing_email: 
                raise forms.ValidationError('duplicate_email', code='duplicate_email')                
                
            else: 
                return email            
        
        else: 
            return email

user_profile/views.py
from django.shortcuts import render

from django.template.context_processors import csrf
from django.template import RequestContext, loader,Context

from django.http import HttpResponse
from django.http import HttpResponseRedirect

from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

from .models import UserProfile
from .models import ShopProfile
from .models import CustomerProfile

from .forms import UserProfileForm
from .forms import MyProfileCustomerForm
from .forms import MyProfileShopForm

from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives


def my_password_reset(request):
    # calls django.contrib.auth.views.password_reset with its customisations
    # and returns the result
    response = auth_views.password_reset(request,
                                         template_name='user_profile/password_reset.html',
                                         html_email_template_name='user_profile/password_reset_email.html',
                                         subject_template_name = 'user_profile/password_reset_subject.txt',
                                         post_reset_redirect='/accounts/password_reset_done',
                                         from_email='passwords@gooshibegooshi.com',
                                         current_app='user_profile')
    return response


def my_password_reset_done(request):

    return render(request,'user_profile/password_reset_done.html')


def my_password_reset_confirm(request,uidb64,token):
    response = auth_views.password_reset_confirm(request,
                                                 uidb64=uidb64,
                                                 token=token,
                                                 template_name='user_profile/password_reset_confirm.html',
                                                 post_reset_redirect='/accounts/password_reset_complete',
                                                 current_app='user_profile')

    return response


def my_password_reset_complete(request):

    return render(request,'user_profile/password_reset_complete.html')

@login_required
def my_password_change(request):

    template_name='user_profile/password_change.html'
    post_change_redirect='/accounts/my_password_change_done/'

    return auth_views.password_change(request,
                                      template_name = template_name,
                                      post_change_redirect = post_change_redirect )

@login_required
def my_password_change_done(request):

	template_name = 'user_profile/password_change_done.html'
	response = auth_views.password_change_done(request,template_name=template_name)

	# send email to notify the user that his password has changed.
	plaintext = loader.get_template('user_profile/password_change_email_done.txt')
	htmly = loader.get_template('user_profile/password_change_email_done.html')
	subject = loader.get_template('user_profile/password_change_email_done_subject.html')

	context = Context({"empty":"empty"})
	subject_content = subject.render(context).replace('\n',' ')
	text_content = plaintext.render(context)
	html_content = htmly.render(context)

	from_email = 'passwords@gooshibegooshi.com'
	recipient_list = [request.user.email]

	msg = EmailMultiAlternatives(subject_content, text_content, from_email, recipient_list)
	msg.attach_alternative(html_content, "text/html")
	msg.send()

	return response

@login_required
def myprofile(request):

    user_profile = UserProfile.objects.get(user=request.user)

    if request.method == 'POST' :

        # get the initial data for the MyProfileShopForm.
        data = {}
        data['email'] = request.user.email
        data['mobile'] = user_profile.mobile
        data['email_subscription'] = user_profile.email_subscription

        if user_profile.is_shop:

            shop_profile = ShopProfile.objects.get(user_profile = user_profile)

            # additional data about the shop
            data['address'] = shop_profile.address
            data['landline'] = shop_profile.landline
            data['reward'] = shop_profile.reward
            data['bank_card_number'] = shop_profile.bank_card_number
            data['account_holder'] = shop_profile.account_holder

            # reconstruct the form
            shop_details_form = MyProfileShopForm(request.POST,initial=data)

            if shop_details_form.is_valid() & shop_details_form.has_changed():

                # get the data out of the forms.
                email = shop_details_form.cleaned_data['email']
                mobile = shop_details_form.cleaned_data['mobile']
                email_subscription = shop_details_form.cleaned_data['email_subscription']
                address = shop_details_form.cleaned_data['address']
                landline = shop_details_form.cleaned_data['landline']
                bank_card_number = shop_details_form.cleaned_data['bank_card_number']
                account_holder = shop_details_form.cleaned_data['account_holder']



                # if the email has changed, make sure that the new email is still unique
#                if "email" in shop_details_form.changed_data:
#                    return HttpResponse("changed email")
#                else:
#                    return HttpResponse("nothing changed")

                # save the data into the database
                request.user.email = email

                user_profile.mobile = mobile
                user_profile.email_subscription = email_subscription

                shop_profile.address = address
                shop_profile.landline = landline
                shop_profile.bank_card_number = bank_card_number
                shop_profile.account_holder = account_holder

                request.user.save()
                user_profile.save()
                shop_profile.save()

        else:
            # user is not a shop

            # reconstruct the form
            customer_details_form = MyProfileCustomerForm(request.POST,initial=data)

            if customer_details_form.is_valid() & customer_details_form.has_changed() :

                # get the data out of the form
                email = customer_details_form.cleaned_data['email']
                mobile = customer_details_form.cleaned_data['mobile']
                email_subscription = customer_details_form.cleaned_data['email_subscription']

                # save it to the database.
                user_profile = UserProfile.objects.get(user=request.user)
                request.user.email = email
                user_profile.mobile = mobile
                user_profile.email_subscription = email_subscription

                user_profile.save()
                request.user.save()

    else:
        # if the request does not have POST method

        data = {}
        data['email'] = request.user.email
        data['mobile'] = user_profile.mobile
        data['email_subscription'] = user_profile.email_subscription

        # depending on the type of the user, the template will respond differently.
        #args['is_shop'] = user_profile.is_shop

        if user_profile.is_shop:

            shop_profile = ShopProfile.objects.get(user_profile = user_profile)
            data['address'] = shop_profile.address
            data['landline'] = shop_profile.landline
            data['reward'] = shop_profile.reward
            data['bank_card_number'] = shop_profile.bank_card_number
            data['account_holder'] = shop_profile.account_holder



            shop_details_form = MyProfileShopForm(initial=data)

        else:
            customer_details_form = MyProfileCustomerForm(initial=data)


    args = {}
    args.update(csrf(request))
    args['is_shop'] = user_profile.is_shop

    if user_profile.is_shop:
        args['shop_details_form'] = shop_details_form
    else:
        args['customer_details_form'] = customer_details_form

    return render(request,'user_profile/myprofile.html',args)


def register(request):

    if request.method == 'POST':

        user_form = UserCreationForm(request.POST, prefix='user')
        user_profile_form = UserProfileForm(request.POST, prefix = 'userprofile')

        if user_profile_form.is_valid() & user_form.is_valid() :


            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password1']
            email = user_profile_form.cleaned_data['email']   # we get user email using an instance of UserProfileForm

            user = User.objects.create_user(username=username, password=password, email=email)

            user_profile = UserProfile()
            user_profile.user = user

            user_profile.is_shop = user_profile_form.cleaned_data['is_shop']
            user_profile.email_subscription = True
            user_profile.mobile = user_profile_form.cleaned_data['mobile']

            user_profile.save()

            if user_profile.is_shop:
                # if the user represents a shop
                shop_profile = ShopProfile()
                shop_profile.user_profile = user_profile
                shop_profile.address = user_profile_form.cleaned_data['address']
                shop_profile.landline = user_profile_form.cleaned_data['landline']
                shop_profile.bank_card_number = ''
                shop_profile.account_holder = ''
                shop_profile.save()


            else:
                # if the user represents a normal customer (as opposed to a shop)
                customer_profile = CustomerProfile()
                customer_profile.user_profile = user_profile
                customer_profile.save()


            return HttpResponseRedirect("/accounts/register_success/")


    else:

user_profile/templates/user_profile/invalid.html
{% extends 'bitasync_site/base.html' %}
{% load staticfiles  %}

{% block title %} بیتاسینک -> {% endblock title %}


	

	{% block extracss %} 
		 
	{% endblock extracss %}

	{% block extrajs %}
		
	{% endblock extrajs %}
  

	{% block section %} 
		<section class="main-section" id="service"><!--main-section-start-->
			<div class="container">

				<div class="row">
					<h2> You login details are invalid </h2>
					<h3 style="text-align:center"> Click <a href="/accounts/login/"> here </a> to login again.  </h3>

				</div>
			 </div>
            
       
		</section>
	{% endblock section %}	

user_profile/templates/user_profile/loggedin.html
{% extends 'bitasync_site/base.html' %}
{% load staticfiles  %}

{% block title %} بیتاسینک -> {% endblock title %}


	

	{% block extracss %} 
		 
	{% endblock extracss %}

	{% block extrajs %}
		
	{% endblock extrajs %}
  

	{% block section %} 
		<section class="main-section" id="service"><!--main-section-start-->
			<div class="container">

				<div class="row">
					<h2> Hi {{fullname}}, you are logged in! </h2>
					Click <a href="/accounts/logout/"> Here </a> to log out.

				</div>
			 </div>
            
       
		</section>
	{% endblock section %}	

user_profile/templates/user_profile/login.html
{% extends 'bitasync_site/base.html' %}
{% load staticfiles  %}

 	{% block title %} بیتاسینک -> ورود {% endblock title %}


	

	{% block extracss %} 
		  <link rel="stylesheet" href="{% static "user_profile/css/login.css" %}">
	{% endblock extracss %}

	{% block extrajs %}
			<script src="{% static "user_profile/js/login.js" %}"></script>
	{% endblock extrajs %}
   



	{% block section %} 
   
	   <section class="main-section"><!--main-section-start-->
			<div class="container">
				<!--<h2></h2>
				<h6></h6>-->
				<div class="row">
				
					
					
					<div class="col-sm-7 col-sm-offset-3 form-box">
									<div class="form-top">
										<div class="form-top-left" style="margin-top: 20px;">
											<h3> اگر هنوز عضو "گوشی ب گوشی" نیستید
												<a href='/accounts/register/' style="color:red"> 	ثبت نام </a>
												کنید</h3>
											<!--<p><a href='/accounts/register/' style="color:red"> اگر هنوز عضو بیتاسینک نیستید ثبت نام کنید</a></p>
										-->
										</div>
										<div class="form-top-right">
											<i class="fa fa-users"></i>
										</div>
									</div>
									<!--<div class="form-bottom"></div>-->
					</div>
				
				</div>	
				<br>
		

				<div class="row">
								<!--<div class="col-sm-6 phone">
									<img src="{% static "user_profile/assets/img/iphone.png" %}" alt="">
								</div>-->
								 <div class="col-sm-7 col-sm-offset-3 form-box">
									<div class="form-top">
										<div class="form-top-left">
											<h3></h3>
											<p style="font-family:b mehr">نام کاربری و کلمه عبور خود را وارد کنید</p>
										</div>
										<div class="form-top-right">
											<i class="fa fa-lock"></i>
										</div>
									</div>
									<div class="form-bottom">

							 <form role="form" action='' method='post' class="login-form"> {% csrf_token  %}
			{{ form.field_errors }}		                    	
		<div class="form-group">
												<label class="sr-only" for="{{ form.username.id_for_label }}">نام کاربری</label>
												<input type="text" name="{{ form.username.html_name }}" placeholder="نام کاربری ..." class="form-username form-control" id="{{ form.username.id_for_label }}">
						
											</div>
											<div class="form-group">
												<label class="sr-only" for="{{ form.password.id_for_label }}">کلمه عبور</label>
												<input type="password" name="{{ form.password.html_name }}" placeholder="کلمه عبور ..." class="form-password form-control" id="{{ form.password.id_for_label }}">
												
											{% if form.non_field_errors  %}											
                                                <span > <strong style="color:red">
                                                    اطلاعات وارد شده صحیح نیست. لطفا دوباره امتحان کنید. 
                                                </strong> </span>                                                                                       
                                            {% endif %}
											</div>
											
                                            
											
											<button type="submit" class="btn">ورود</button>
											<br><br>
		<a href='/accounts/password_reset/'> <b>کلمه عبور خود را فراموش کرده اید؟</b></a><br>
	
		
								 

										</form>
									</div>
								</div>
							</div>
						
		   
		   </div>
				


		</section><!--main-section-end-->

	{% endblock section %}		

user_profile/templates/user_profile/myprofile.html
{% extends 'bitasync_site/base.html' %}
{% load staticfiles  %}

{% block title %} بیتاسینک -> ناحیه کاربری {% endblock title %}


	

	{% block extracss %} 
		 <link rel="stylesheet" href="{% static "user_profile/css/profile.css" %}">
	{% endblock extracss %}

	{% block extrajs %}
		<script src="{% static "user_profile/js/profile.js" %}"></script>
	{% endblock extrajs %}
  

	{% block section %} 
		<section class="main-section" id="service"><!--main-section-start-->
		  <div class="container">
		   	  <div class="row">
                    	<!--<div class="col-sm-6 phone">
                    		<img src="{% static "user_profile/assets/img/iphone.png" %}" alt="">
                    	</div>-->
               <div class="col-sm-8 form-box col-sm-offset-2">
				<div class="form-top">
					<div class="form-top-left">
					<h3>حساب کاربری شما در بیتاسینک	</h3>
					
					<h5 style="font-family: b roya ! important; font-size: 17px;">  در صورت نیاز می توانید مشخصات کاربری خود را تغییر دهید			</h5>
					</div>
					<div class="form-top-right">
						<i class="fa fa-pencil"></i>
					</div>
				</div>
				<div class="form-bottom">
					
					
					
					
			<form role="form" action="" method="post" class="registration-form">
						{% csrf_token  %}
						{{ form.field_errors }}	
<!---------------------------------------------------------------------------------------->
			{% if is_shop %}
				
			<!--<div class="form-group">
				<label class="rglabel" for="{{ shop_details_form.username.id_for_label }}"> نام کاربری</label>
				<input type="text" name="{{ shop_details_form.username.html_name }}" placeholder="نام کاربری ..." class="form-first-name form-control" id="{{ shop_details_form.username.id_for_label }}">
			</div>-->

			

			<div class="form-group">			                    
			<label class="rglabel" for="{{ shop_details_form.email.id_for_label }}">ایمیل</label>
				<input style="text-align: right; direction: ltr;" value="{{ shop_details_form.email.value }}" type="email" name="{{ shop_details_form.email.html_name }}" placeholder="ایمیل" class="form-email form-control" id="{{ shop_details_form.email.id_for_label }}">
			{% if shop_details_form.email.errors %}
                    <span> <strong style="color:red">این ایمیل قابل قبول نیست. یک ایمیل جدید وارد نمایید.</strong> </span>
            {% endif %}
				

			</div>

			<div class="form-group">			                    
			<label class="rglabel" for="{{ shop_details_form.mobile.id_for_label }}">موبایل</label>
				<input value="{{ shop_details_form.mobile.value }}" type="text" name="{{ shop_details_form.mobile.html_name }}" placeholder="موبایل " class="form-control" id="{{ shop_details_form.mobile.id_for_label }}">
			</div>

			

			<div class="form-group">			                    
			<label class="rglabel" for="{{ shop_details_form.address.id_for_label }}">آدرس</label>
				<input value="{{ shop_details_form.address.value }}" type="text" name="{{ shop_details_form.address.html_name }}" placeholder="آدرس" class="form-control" id="{{ shop_details_form.address.id_for_label }}">
			</div>

			<div class="form-group">			                    
			<label class="rglabel" for="{{ shop_details_form.landline.id_for_label }}">تلفن ثابت</label>
				<input style="text-align: right; direction: ltr;" value="{{ shop_details_form.landline.value }}" type="text" name="{{shop_details_form.landline.html_name }}" placeholder="تلفن ثابت - به همراه کد شهر ( اختیاری )" class="form-control" id="{{ shop_details_form.telephone.id_for_label }}">
			</div>

			<div class="form-group">			                    
			<label class="rglabel" style="" for="{{ shop_details_form.email_subscription.id_for_label }}">
			خبرنامه بیتاسینک؟
			</label>
			<div style="width: 60%; display: inline-block;">
				<input style="float: right; width: 10px ! important; height: 10px;" type="checkbox" name="{{ shop_details_form.email_subscription.html_name }}" class="form-control" id="{{ shop_details_form.email_subscription.id_for_label }}">
			</div>
				</div>

			{% if shop_details_form.email_subscription.value %} <script> $('#id_email_subscription').prop('checked',true) </script> {% endif %}
				
			<div class="form-group" style="clear: both;">			                    
				<label class="rglabel" for="{{ shop_details_form.reward.id_for_label }}">
			  بستانکاری 
				</label>
				<input readonly="" value="{{ shop_details_form.reward.value }}" type="text" name="{{ shop_details_form.reward.html_name }}" placeholder="جایزه" class="form-email form-control" id="{{ shop_details_form.reward.id_for_label }}">
			</div>
			
			<div class="form-group" >			                    
				<label class="rglabel" for="{{ shop_details_form.bank_card_number.id_for_label }}">شماره کارت بانکی</label>
				
				<input style="text-align: right; direction: ltr;" value="{{ shop_details_form.bank_card_number.value }}" type="text" name="{{ shop_details_form.bank_card_number.html_name }}" placeholder="شماره کارت بانکی" class="form-control" id="{{ shop_details_form.bank_card_number.id_for_label }}">
			</div>	
				
			<div class="form-group">			                    
			<label class="rglabel" for="{{ shop_details_form.account_holder.id_for_label }}">نام دارنده حساب</label>
				<input value="{{ shop_details_form.account_holder.value }}" type="text" name="{{ shop_details_form.account_holder.html_name }}" placeholder="دارنده حساب" class="form-email form-control" id="{{ shop_details_form.account_holder.id_for_label }}">
			</div>	
				
				
				<!---------------------------------------------------------------------------------------->
			{% else %}

			<div class="form-group">			                    
			<label class="rglabel" for="{{ customer_details_form.email.id_for_label }}">
			ایمیل
			</label>
				<input style="text-align: right; direction: ltr;" value="{{ customer_details_form.email.value }}" type="email" name="{{ customer_details_form.email.html_name }}" placeholder="ایمیل" class="form-email form-control" id="{{ customer_details_form.email.id_for_label }}">
			
			
			{% if customer_details_form.email.errors %}
                    <span> <strong style="color:red">این ایمیل قابل قبول نیست. یک ایمیل جدید وارد نمایید.</strong> </span>
            {% endif %}	
				
			</div>

			<div class="form-group">			                    
			<label class="rglabel" for="{{ customer_details_form.mobile.id_for_label }}">موبایل</label>
				<input value="{{ customer_details_form.mobile.value }}" type="text" name="{{ customer_details_form.mobile.html_name }}" placeholder="موبایل" class="form-control" id="{{ customer_details_form.mobile.id_for_label }}">
			</div>

			<div class="form-group">			                    
			<label class="rglabel" style="float:right;" for="{{ customer_details_form.email_subscription.id_for_label }}">
			دریافت خبرنامه بیتاسینک؟
			</label>
				<input  style="width: 5px ! important; position: relative; float: right; bottom: 7px; right: 30px;"type="checkbox" name="{{ customer_details_form.email_subscription.html_name }}" class="form-control" id="{{ customer_details_form.email_subscription.id_for_label }}">
			</div>

			{% if customer_details_form.email_subscription.value %} <script> $('#id_email_subscription').prop('checked',true) </script> {% endif %}



			{% endif %}
				
				
			{{ form.non_field_errors }}
				
 		  		 <button type="submit" class="btn">تغییر پروفایل</button>
			               
					<a style="float: left; text-decoration: none; padding: 5px; background-color: #99ccff; border-radius: 5px; margin-top: 10px; color: black;" href="/accounts/password_change">تغییر رمز عبور</a>	
					<br>
		</form>
		                  
				   
				   
				   
				   </div>
                        </div>
                    </div>
        	  
		<!--	  <div class="row">
			
							
				{% if is_shop %}

				<form action="/accounts/myprofile/" method="post">
				{% csrf_token %}
				<table border="1">
				{{shop_details_form.as_table}}
				</table>

				<input type='submit' value='submit'>

				</form>

				{% else %}

				<form action="/accounts/myprofile/" method="post">
				{% csrf_token %}
				<table border="1">
				{{customer_details_form.as_table}}
				</table>

				<input type='submit' value='submit'>

				</form>

				<hr>
				<a href="/accounts/password_change">Password Reset</a>

				{% endif %}
		
		</div>-->
		
			
			</div>
            
       
		</section>
	{% endblock section %}	

user_profile/templates/user_profile/password_change_done.html
{% extends 'bitasync_site/base.html' %}
{% load staticfiles  %}

{% block title %} گوشی ب گوشی -> رمز عبور{% endblock title %}


	

	{% block extracss %} 
		 
	{% endblock extracss %}

	{% block extrajs %}
		
	{% endblock extrajs %}
  

	{% block section %} 
		<section class="main-section" id="service"><!--main-section-start-->
			<div class="container">

				<div class="row">
					<h3 style="text-align:center"> 
					    رمز عبور شما با موفقیت تغییر یافت. جهت تایید به زودی یک ایمیل از "گوشی ب گوشی" دریافت خواهید کرد.
					</h3>
					
					<hr>

				</div>
			 </div>
            
       
		</section>
	{% endblock section %}	

user_profile/templates/user_profile/password_change_email_done.html
{% load i18n %}

{% autoescape off %}
<div style="direction: rtl">
سلام
<br><br>

رمز عبور شما روی وب سایت گوشی ب گوشی با موفقیت تغییر یافت. 

<br> <br>
با مهر
<br> 
تیم پشتیبانی "گوشی ب گوشی"

</div>
{% endautoescape %}

user_profile/templates/user_profile/password_change_email_done_subject.html
 گوشی ب گوشی - رمز عبور

user_profile/templates/user_profile/password_change_form.html
<h2> Password Change Page</h2>

<p> Please enter your new password and click OK. </p>

<hr>

<form action="/accounts/password_change/" method="post">
{{form.as_table}}
<input type="submit" value="OK" />
</form>

user_profile/templates/user_profile/password_reset_complete.html
{% extends 'bitasync_site/base.html' %}
{% load staticfiles  %}

{% block title %} 
گوشی ب گوشی -> رمز ورود
{% endblock title %}


	{% block extracss %} 
		 
	{% endblock extracss %}

	{% block extrajs %}
		
	{% endblock extrajs %}
  

	{% block section %} 
		<section class="main-section" id="service"><!--main-section-start-->
			<div class="container">

				<div class="row">
					
					<h3 style="font-size:25px ; text-align:center">
					       رمز عبور با موفقیت تغییر یافت. اکنون می توانید با رمز عبور جدید وارد شوید.
					</h3>
					
				</div>
			 </div>
            
       
		</section>
	{% endblock section %}	