ads/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import views

urlpatterns = [
    url(r'^kaspersky/$', views.kaspersky_android),
]

bitasync/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from bitasync_site import views


urlpatterns = [
    url(r'^$', views.homepage),
    url(r'^api-auth/', include('rest_framework.urls',namespace='rest_framework')),
    url(r'^162294.txt$', views.test_function),
    url(r'^about_us/', views.about_us),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^bitasync/', include('bitasync_site.urls')),
    url(r'^accounts/', include('user_profile.urls')),
    url(r'^code_test/', include('code_test.urls')),
    url(r'^coupons/', include('coupons.urls')),
    url(r'^guides/', include('guides.urls')),
    url(r'^payment/', include('payment.urls')),
    url(r'^shop_billing/', include('shop_billing.urls')),
    url(r'^ads/', include('ads.urls')),
    url(r'^access_control/', include('access_control.urls')),
    url(r'^telepromo_integration/', include('telepromo_integration.urls')),
]

bitasync_site/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^help_mobile_version/$', views.help_mobile_version),
    url(r'^data_transfer_plans/$', views.data_transfer_plans),
    url(r'^contact_us/$', views.contact_us_page),
    url(r'^thanks_contact_us/$', views.thanks_contact_us),
    url(r'^activate/(?P<plan_name>\w\d)/$', views.activate_plan),
    url(r'^activate/payment_failed/(?P<plan_name>\w\d)/$', views.payment_failed),
    url(r'^activate/payment_success/(?P<plan_name>\w\d)/(?P<follow_up_number>(\d|\w)+)/$',views.payment_success),
    url(r'^terms_conditions/$', views.terms_conditions),
]

payment/urls.py
from django.conf.urls import include, url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    url(r'^(?P<plan_name>\w\d)/$', views.pay_for_a_plan),
    url(r'^initialise_payment/(?P<plan_name>\w\d)/$', views.initialise_payment_payline),
    url(r'^result_payline/(?P<pending_purchase_hashcode>[0-9A-Za-z]{1,32})/$',views.result_payline),
]
urlpatterns = format_suffix_patterns(urlpatterns)

bitasync_site/models.py
from django.db import models
from durationfield.db.models.fields.duration import DurationField
import datetime

from django.contrib.auth.models import User

class Data_Transfer_Plan(models.Model):

    plan_name = models.CharField(max_length=10)
    freq = models.IntegerField(default=0, null=True, blank=True)
    duration = DurationField(null=True, blank=True)
    description = models.CharField(max_length=1000, default="data plan description")
    long_description = models.CharField(max_length=1000, default="long description for a data transfer plan")
    price = models.IntegerField(default = 0)
    


    def __unicode__(self):
        return self.plan_name

class Contact_Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    message = models.CharField(max_length=1000)
    call_back_request = models.NullBooleanField(null=True,blank=True)
    phone_number= models.CharField(null=True,blank=True,max_length=20)

class B2C_Coupon:
    pass


class B2S2C_Coupon:
    pass

payment/models.py
from django.db import models
from django.contrib.auth.models import User
from bitasync_site.models import Data_Transfer_Plan
from django.db.models import signals
from .signals import pending_purchase_created



class Purchase(models.Model):

    user = models.ForeignKey(User, related_name='customer')
    data_transfer_plan = models.ForeignKey(Data_Transfer_Plan)
    # to do. store agents' name in the database, and give her some rewards.
    # this can be used in the admin interface that we design for our customer
    # service team.
    # assisting_agent = models.ForeignKey(Sales_Agent)

    purchase_date = models.DateField(auto_now_add=True)
    amount_paid = models.FloatField(default=0)
    follow_up_number = models.CharField(max_length=100, null=True, blank=True)

    # access control.
    remaining_allowance_frequency = models.IntegerField(default=0)

    # managing purchase records that are associated with
    # shops selling a post-paid license
    shop_debited = models.BooleanField(default=False)
    # we store the shop entitiy related to the shop
    selling_shop = models.ForeignKey(User, blank=True, null=True,
                                     related_name='selling_shop')

    gateway = models.CharField(max_length=100, null=True,
                               blank=True, default="unspecified")

    def __unicode__(self):
        return (self.data_transfer_plan).plan_name + "_" + (self.user).username

class PendingPurchase(models.Model):

    data_transfer_plan = models.ForeignKey(Data_Transfer_Plan)
    user = models.ForeignKey(User, related_name='end_customer')

    hashcode = models.CharField(max_length=50, null = True, blank=True)
    time_created =  models.DateField(auto_now_add=True)

signals.post_save.connect(pending_purchase_created, sender=PendingPurchase, weak=False)

bitasync_site/forms.py
from django import forms

class Contact_us(forms.Form): 
    
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    call_back = forms.BooleanField(required=False)
    phone_number = forms.CharField(max_length=20,required=False)
    
    
    

bitasync_site/views.py
from django.http import HttpResponse, HttpResponseRedirect
from .models import Data_Transfer_Plan
from django.template import RequestContext, loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render

from django.core.mail import send_mail
from .forms import Contact_us

from models import Contact_Comment


from coupons.models import Coupon
from user_profile.models import UserProfile

from django.template.context_processors import csrf

from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail

import hashlib

from utilities import utility_functions

from coupons.forms import AddCouponForm


def help_mobile_version(request):
    return render(request,'bitasync_site/help_mobile_version.html') 


def thanks_contact_us(request):

    return render(request, 'bitasync_site/thanks_contact_us.html')


def contact_us(request):

    if request.method == "POST":

        form = Contact_us(request.POST)

        if form.is_valid():

            # send an eamil to the user acknowledging that his message was received.
            email = form.cleaned_data['email']
            email_message = """Thanks for contacting Bit@Sync.
            Our customer service team will get in touch shortly.
            """
            subject = "Thanks for Contacting Bit@Sync."
            from_email = "outreach@bitasync.com"
            recipient_list = [email]

            send_mail(subject=subject,
                     message=email_message,
                     from_email = from_email,
                     recipient_list=recipient_list,
                     fail_silently=False)


            # add user message to the database.

            comment = Contact_Comment()
            comment.name = form.cleaned_data['name']
            comment.message = form.cleaned_data['message']
            comment.email = email
            comment.call_back_request = form.cleaned_data['call_back']
            comment.phone_number = form.cleaned_data['phone_number']

            comment.save()

            return HttpResponseRedirect("/bitasync/thanks_contact_us/")

        else:

            args= {}
            args.update(csrf(request))
            args['form']=form


            template = loader.get_template('bitasync_site/index.html')
            context = RequestContext(request,args)
            return HttpResponse(template.render(context))


    else:
        form = Contact_us()

        args= {}
        args['form']=form


        template = loader.get_template('bitasync_site/index.html')
        context = RequestContext(request,args)
        return HttpResponse(template.render(context))

def contact_us_page(request):



    if request.method == "POST":

        form = Contact_us(request.POST)

        if form.is_valid():

            # send an eamil to the user acknowledging that his message was received.
            email = form.cleaned_data['email']
            email_message = """Thanks for contacting Bit@Sync.
            Our customer service team will get in touch shortly.
            """
            subject = "Thanks for Contacting Bit@Sync."
            from_email = "outreach@bitasync.com"
            recipient_list = [email]

            send_mail(subject=subject,
                     message=email_message,
                     from_email = from_email,
                     recipient_list=recipient_list,
                     fail_silently=False)


            # add user message to the database.

            comment = Contact_Comment()
            comment.name = form.cleaned_data['name']
            comment.message = form.cleaned_data['message']
            comment.email = email
            comment.call_back_request = form.cleaned_data['call_back']
            comment.phone_number = form.cleaned_data['phone_number']

            comment.save()

            return HttpResponseRedirect("/bitasync/thanks_contact_us/")

        else:

            args= {}
            args.update(csrf(request))
            args['form']=form


            template = loader.get_template('bitasync_site/contact_us.html')
            context = RequestContext(request,args)
            return HttpResponse(template.render(context))


    else:
        form = Contact_us()

        args= {}
        args['form']=form


        template = loader.get_template('bitasync_site/contact_us.html')
        context = RequestContext(request,args)
        return HttpResponse(template.render(context))


def homepage(request):

    return render(request,'bitasync_site/homepage_responsive.html')

    #return contact_us(request);
	#return render(request, 'bitasync_site/index.html')


def data_transfer_plans(request):

    # return thh list of data_transfer_plans as a list.
    plans = Data_Transfer_Plan.objects.all()

    if not plans:
        raise Http404("No data transfer plans found")

    template = loader.get_template('bitasync_site/data_transfer_plans.html')
    context = RequestContext(request, {'plan_list': plans})
    return HttpResponse(template.render(context))

@login_required
def activate_plan(request,plan_name):

    # check that the model chosen is correct.
    valid_plans = ["L1","L2","L5","U1","U3","U6"]

    user_profile = UserProfile.objects.get( user = request.user )

    context={}
    context.update(csrf(request))
    context['coupon_code_entered'] = False


    if plan_name not in valid_plans :
      raise Http404("Data transfer selected is not valid.")

    if request.method == "POST":
        # a new coupon code has been entered. Check if the coupon is valid and enter the code.

        context['coupon_code_entered'] = True
        form = AddCouponForm(request.POST)

        if form.is_valid():

            hashcode = form.cleaned_data['hashcode']

            # associate the code to the customer profile
            try:
                coupon = Coupon.objects.get( hashcode = hashcode )
                coupon.user_profile = user_profile
                coupon.save()
                context['wrong_coupon_entered'] = False

            except Coupon.DoesNotExist:
                # the coupon entered does not exist in the database
                context['wrong_coupon_entered'] = True


        else:
            # form is not valid
            context['wrong_coupon_entered'] = True




        # request.method is not POST
        # do the pricing given the customer's coupons

    all_plans = Data_Transfer_Plan.objects.all()
    plan = utility_functions.get_plan_by_name(all_plans,plan_name)

        # check if the user has any discount coupon.
    user_existing_coupons = Coupon.objects.filter( user_profile = user_profile )

    selected_plan = utility_functions.create_temp_plan(plan, user_existing_coupons)
    alternative_plans = get_alternative_plans(all_plans,selected_plan, user_existing_coupons)

            # set up the context

    context['selected_plan'] = selected_plan
    context['alt_plan_0'] = alternative_plans[0]
    context['alt_plan_1'] = alternative_plans[1]
    context['alt_plan_2'] = alternative_plans[2]
    context['alt_plan_3'] = alternative_plans[3]
    context['alt_plan_4'] = alternative_plans[4]

            # setting the context, depending on whether the customer has any coupons available
    if not user_existing_coupons:
        context['coupon_available'] = False

    else:
                # if the customer has some coupons
        context['coupon_available'] = True
        context['existing_coupons'] = user_existing_coupons


    add_coupon_form = AddCouponForm()
    context['add_coupon_form'] = add_coupon_form

    return render(request,'bitasync_site/payment_with_coupons.html',context)


@login_required
def payment_failed(request,plan_name):

    valid_plans = ["L1","L2","L5","U1","U3","U6"]
    if plan_name not in valid_plans :
        raise Http404("Data transfer selected is not valid.")
    else:

        if request.method == "POST":
            # we should never arrive here.
            # this page contains Contact_us form.
            # when the form is submited, the request is posted to
            # /bitasync/thanks_contact_us, and not here!
            pass

        else:
            context = {}

            form = Contact_us()
            context['plan_name'] = plan_name
            context['form'] = form

            return render(request,"bitasync_site/payment_failed.html",context)

@login_required
def payment_success(request,plan_name,follow_up_number):

    context = {}
    context['plan_name'] = plan_name
    context['img'] = get_image_link(plan_name)
    context['follow_up_number'] = follow_up_number

    return render(request,'bitasync_site/payment_success.html',context)
    #todo: in this page, we can put advertisement related to the mobile phones.


def get_alternative_plans(all_plans, selected_plan, coupons):
    alt_plans = []
    ordered_names = ["L1","L2","L5","U1","U3","U6"]

    for name in ordered_names:
        if name != selected_plan.plan_name:
            alternative_plan = utility_functions.get_plan_by_name(all_plans, name)
            alternative_temp_plan = utility_functions.create_temp_plan(alternative_plan,coupons)
            alt_plans.append(alternative_temp_plan)
    return alt_plans



def terms_conditions(request):
    return render(request,'bitasync_site/terms_conditions.html')

def about_us(request):
    return render(request,'bitasync_site/about_us.html')

def test_function(request):
    return HttpResponse("test")

bitasync_site/templates/bitasync_site/contact_us.html
{% extends 'bitasync_site/base.html' %}
{% load staticfiles  %}

{% block title %} گوشی ب گوشی -> تماس با ما {% endblock title %}


	

	{% block extracss %} 
		 
	{% endblock extracss %}

	{% block extrajs %}
		
	{% endblock extrajs %}
  

	{% block section %} 
		<section class="main-section" id="service"><!--main-section-start-->
			<div class="container">

				 <div class="row" style="direction:rtl">
        	<div class="col-lg-6 col-sm-7 wow fadeInLeft">
            	<!--<div class="contact-info-box address clearfix">
                	<h3><i class=" icon-map-marker"></i>ادرس:</h3>
                	<span>تهران، میدان فردوسی،خیابان موسوی (فرصت) </span>
                </div>-->
                <div class="contact-info-box phone clearfix">
                	<h3><i class="fa-phone"></i> تلفن:</h3>
                	<span>021-88867646</span>
                </div>
                <div class="contact-info-box email clearfix">
                	<h3><i class="fa-pencil"></i> ایمیل:</h3>
                	<span>hello@gooshibegooshi.com</span>
                </div>
            	
				
				
			
            </div>
        	<div class="col-lg-6 col-sm-5 wow fadeInUp delay-05s" style="padding-right: 35px;">
            	<div class="form">
                	<form action="" method="post">
						{% csrf_token %}
						{{ form.field_errors }}	
						
					<input id= "{{ form.name.id_for_label }}" class="input-text" type="text" name="{{ form.name.html_name }}" value="نام *" onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;">
                    <input id="{{ form.email.id_for_label }}" class="input-text" type="text" name="{{ form.email.html_name }}" value="ایمیل *" onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;">
                   	<textarea id="{{ form.message.id_for_label }}"  name="{{ form.message.html_name }}" class="input-text text-area" cols="0" rows="0" onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;">پیام *</textarea>
                    
					<label for="{{ form.call_back.id_for_label }}">
با انتخاب این گزینه ما با شما تماس خواهیم گرفت.
</label> <input id="{{ form.call_back.id_for_label }}" name="{{ form.call_back.html_name }}" class="" type="checkbox" 	/>
                    <input id="{{ form.phone_number.id_for_label }}" class="input-text" type="text" name="{{ form.phone_number.html_name }}" value="شماره تماس *" onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;">
                
					
					<input class="input-btn" type="submit" value="ارسال پیام">
						{{ form.non_field_errors }}
				</form>

                </div>	
            </div>
        </div>
			 </div>
            
       
		</section>
	{% endblock section %}	

bitasync_site/templates/bitasync_site/data_transfer_plans.html
{% extends 'bitasync_site/base.html' %}
{% load staticfiles  %}

{% block title %} بیتاسینک -> {% endblock title %}


	

	{% block extracss %} 
		 
	{% endblock extracss %}

	{% block extrajs %}
		
	{% endblock extrajs %}
  

	{% block section %} 
		<section class="main-section" id="service"><!--main-section-start-->
			<div class="container">

				<div class="row">
					{% if plan_list %}

						

								<style>
								table, th, td {
									border: 1px solid black;
								}

								td {
									padding: 15px;
								}
								</style>
							<table>
							  <tr>
								<th> Plan Name </th>
								<th> Frequency </th>
								<th> Duration </th>
								<th> Description </th>
								<th> Purchase Link </th>
							  </tr>

							  {% for plan in plan_list %}

									<tr>

										<td> {{plan.plan_name}} </td>
										<td> {{plan.freq}} </td>
										<td> {{plan.duration}} </td>
										<td> {{plan.description}} </td>
										<td> <a href="/bitasync/activate/{{ plan.plan_name }}/" >  Activate this plan  </a> </td>

									</tr>

							  {% endfor %}

							</table>

							{% else %}
							  <p>
								No data transfer plans available.
							  </p>
							{% endif %}

				</div>
			 </div>
            
       
		</section>
	{% endblock section %}	

bitasync_site/templates/bitasync_site/payment.html
{% extends 'bitasync_site/base.html' %}
{% load staticfiles  %}

{% block title %} بیتاسینک -> فعالسازی طرح انتخابی  {% endblock title %}


	

	{% block extracss %} 
		 
	{% endblock extracss %}

	{% block extrajs %}
		
	{% endblock extrajs %}
  

	{% block section %} 
		<section class="main-section" id="service"><!--main-section-start-->
			<div class="container">

			
				  <div class="row" style="text-align:center">
        				<img src={{image_link}}>

						<br><br>

						<div>
							<span> عنوان طرح:  </span> <span> {{plan.description}} </span>
						</div>

						<br>

						<div>
							<span> هزینه:  </span> <span> {{plan.price}}</span><span> تومان </span>
						</div>
						<br>



						<form action="/bitasync/activate/{{plan.plan_name}}/" method="post">   
							{% csrf_token  %}   
							<input type="submit" value="پرداخت الکترونیکی">    
						</form>

             
      				 </div>
			</div>
			
            
       
		</section>
	{% endblock section %}	

bitasync_site/templates/bitasync_site/payment_with_coupons.html
{% extends 'bitasync_site/base.html' %}
{% load staticfiles  %}

{% block title %} گوشی ب گوشی -> فعال سازی  {% endblock title %}


	

	{% block extracss %} 
		  <link rel="stylesheet" href="{% static "user_profile/css/activate.css" %}">
	{% endblock extracss %}

	{% block extrajs %}
		
	{% endblock extrajs %}
  

	{% block section %} 
		<section class="main-section" id="service"><!--main-section-start-->
		
			<div class="container">

				
				 <div class="row">
					
					
					 <div class="col-md-4  pull-right">
						<div id="palanselected" class="offer offer-danger">
							<div class="shape">
								<div class="shape-text">
															
								</div>
							</div>
							<div class="offer-content">
								<h3 class="lead">
									
								</h3>
						
									 <h3>طرح انتخاب شده</h3>
					<hr>
							
					
						 <br/>
							<img src="{{ selected_plan.image_link }}"  alt= "{{ selected_plan.plan_name }}" > <br>
						 <span> {{selected_plan.long_description}} </span><br>

							{% if coupon_available %}
								قیمت = <del> {{selected_plan.original_price }} </del> <span> تومان</span> <br>
								قیمت با احتساب تخفیف: {{selected_plan.discounted_price}} <span> تومان</span>
							{% else %}
								قیمت = {{selected_plan.original_price }} <span> تومان</span>
							{% endif %}
							<br>
							
							<a href="/payment/{{selected_plan.plan_name}}/"><button class="btn btn-danger" type="button">پرداخت الکترونیکی</button></a>
						<br>
							
							</div>
						</div>
					</div>
				
				<div  class=" col-md-8 pull-right">
						<div id="giftcards" class="offer offer-success">
							<div class="shape">
								<div class="shape-text">
																		
								</div>
							</div>
							<div class="offer-content">
								<h3 class="lead">
									
								</h3>						
								{% if not coupon_available %}
						{% else %}
						<h3>کارت های هدیه ی شما	</h3>
						 <hr>
						<table class="table">
							 <tr>
								<th>کارت هدیه</th>
								<th>نرخ تخفیف</th>	
								 <th>تاریخ انقضا</th>
							
							 </tr>  
							{% for coupon in existing_coupons %}
								<tr>
									<td> {{ forloop.counter }} </td>
									<td>{{coupon.discount_rate}}</td>
									<td>{{coupon.expiry_date}}</td>
									
								</tr>  
							{% endfor %}
					    </table>
						{% endif %}
						


							<form action='' method='post'>

								{% csrf_token %}
								{% if coupon_code_entered and wrong_coupon_entered %}
									<input type="text" placeholder="کد وارد شده اشتباه است. لطفا دوباره امتحان کنید" name="hashcode" id="id_hashcode">
								{% endif %}  


								{% if coupon_code_entered and not wrong_coupon_entered %}
									<input type="text" placeholder="کد وارد شده ثبت شد" name="hashcode" id="id_hashcode">
								{% endif %}    



								{% if not coupon_code_entered %}
									<input type="text" placeholder="کد هدیه ی خود را وارد کنید" name="hashcode" id="id_hashcode">    
								{% endif %}    

									<input class="btn btn-success" type="submit" value="اضافه کردن کارت هدیه">


							</form>

					 
					 	
						
							</div>
						</div>
					</div>
					 
					 
					 
								
				</div>
				 	<br><br><hr>
			
				
				
				<div class="row">
					<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 pull-right">
						<div class="offer offer-default">
							<div class="shape">
								<div class="shape-text">
															
								</div>
							</div>
							<div class="offer-content">
								<h3 class="lead">
									
								</h3>
								<!-- <span> {{ alt_plan_0.plan_name  }} </span> <br/>-->
							<img src="{{ alt_plan_0.image_link }}" alt= "{{ alt_plan_0.plan_name }}" > <br/>

						 <div class="comdiv"> {{ alt_plan_0.description }} </div><br/>

							{% if coupon_available %}
							  <span><del>{{alt_plan_0.original_price }} </del></span> <br/>
							 <span>{{alt_plan_0.discounted_price}}</span>
							{% else %}
								  <span> {{alt_plan_0.original_price }}</span> <br/>
							{% endif %}

							<br/>
							<a href="/bitasync/activate/{{alt_plan_0.plan_name}}/"><button type="button">
							سفارش بسته 
							</button></a>
							</div>
						</div>
					</div>
				
					
					<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 pull-right">
						<div class="offer offer-success">
							<div class="shape">
								<div class="shape-text">
																		
								</div>
							</div>
							<div class="offer-content">
								<h3 class="lead">
									
								</h3>						
								
						<!-- </span> <span>{{ alt_plan_1.plan_name  }}</span> <br/>-->
							<img src="{{ alt_plan_1.image_link }}" alt= "{{ alt_plan_1.plan_name }}"> <br/>
							 <div class="comdiv">{{ alt_plan_1.description }} </div><br/>

							{% if coupon_available %}
							  <span> <del>{{alt_plan_1.original_price }}</del></span><span> تومان</span><br/>
								  <span> {{alt_plan_1.discounted_price}}</span><span> تومان</span>

							{% else %}
                        <span> {{alt_plan_1.original_price }}</span><span> تومان</span> <br/>
							{% endif %}
							<br/>
							<a href="/bitasync/activate/{{alt_plan_1.plan_name}}/"><button type="button">
							سفارش بسته 
							</button></a>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 pull-right">
						<div class="offer offer-radius offer-primary">
							<div class="shape">
								<div class="shape-text">
									 						
								</div>
							</div>
							<div class="offer-content">
								<h3 class="lead">
									
								</h3>						
								<!-- </span> <span>{{ alt_plan_2.plan_name  }}</span> <br/>-->
							<img src="{{ alt_plan_2.image_link }}" alt= "{{ alt_plan_2.plan_name }}" > <br/>     
							 <div class="comdiv">  {{ alt_plan_2.description }}  </div><br/>

							{% if coupon_available %}
								  <span><del> {{alt_plan_2.original_price }} </del> </span> <span> تومان</span> <br>
								<span>{{alt_plan_2.discounted_price}}</span> <span> تومان</span> 

							{% else %}
								  <span> {{alt_plan_2.original_price }} </span><span> تومان</span><br>
							{% endif %}
							<br/>
							<a href="/bitasync/activate/{{alt_plan_2.plan_name}}/"><button type="button">
							سفارش بسته 
							</button></a>   
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 pull-right">
						<div class="offer offer-info">
							<div class="shape">
								<div class="shape-text">
									 					
								</div>
							</div>
							<div class="offer-content">
								<h3 class="lead">
									
								</h3>						
								<!-- </span> <span> {{ alt_plan_3.plan_name  }} </span><br/>-->
							<img src="{{ alt_plan_3.image_link }}" alt= "{{ alt_plan_3.plan_name }}" > <br/>

						 <div class="comdiv">{{ alt_plan_0.description }}</div><br/>

							{% if coupon_available %}
						
								  <span> <del> {{alt_plan_3.original_price }} </del></span> <span> تومان</span> <br/>
								  <span>{{alt_plan_3.discounted_price}}</span><span> تومان</span>
							{% else %}
									<span>  {{alt_plan_3.original_price }}</span> <span> تومان</span><br/>
							{% endif %}
							<br/>
							<a href="/bitasync/activate/{{alt_plan_3.plan_name}}/"><button type="button">
							سفارش بسته 
							</button></a>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 pull-right">
						<div class="offer offer-warning">
							<div class="shape">
								<div class="shape-text">
															
								</div>
							</div>
							<div class="offer-content">
								<h3 class="lead">
									
								</h3>						
								<!--</span> <span>{{ alt_plan_4.plan_name  }} </span><br/>-->
							<img src="{{ alt_plan_4.image_link }}" alt= "{{ alt_plan_4.plan_name }}" > <br/>
							  <div class="comdiv"> {{ alt_plan_0.description }}</div><br/>

							{% if coupon_available %}
								 <span>  <del> {{alt_plan_4.original_price }}  </del></span><span> تومان</span><br/>
								  <span>{{alt_plan_4.discounted_price}}</span><span> تومان</span>
							{% else %}
								 <span>{{alt_plan_4.original_price }} </span><span> تومان</span><br/>
							{% endif %}
							<br/>
							<a href="/bitasync/activate/{{alt_plan_4.plan_name}}/"><button type="button">
							سفارش بسته 
							</button></a>
							</div>
						</div>
					</div>
					
				</div>
				
				
				
				
				
					
			
			</div>
  
			
					
			<div class="container">
				
			</div>

			
			
		</section>


	{% endblock section %}	

bitasync_site/templates/bitasync_site/thanks_contact_us.html
{% extends 'bitasync_site/base.html' %}
{% load staticfiles  %}

{% block title %} بیتاسینک -> {% endblock title %}


	

	{% block extracss %} 
		 
	{% endblock extracss %}

	{% block extrajs %}
		
	{% endblock extrajs %}
  

	{% block section %} 
		<section class="main-section" id="service"><!--main-section-start-->
			<div class="container">

				<div class="row">
						 <p> از تماس شما متشکریم</p>
        			<p> برای بازگشت به صفحه اصلی <a href="/"> اینجا </a> را کلیک کنید </p> 
        
				</div>
			 </div>
            
       
		</section>
	{% endblock section %}	